
-- Add station column if not exists
alter table public.menu_items add column if not exists station text;
alter table public.order_items add column if not exists item_station text;

-- Update existing items
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Джингл сет';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Санта';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Мишура';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Снегопад';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Чай Гринч 600 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Чай Груша-конопля 600 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Бабл-ти кокосовый дзен 400 мл';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Тануки';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Аригато';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Филадельфия';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Калифорния';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Прайм';
UPDATE public.menu_items SET station = 'rolls_hot' WHERE title = 'Ролл Калифорния Хот';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Когасэ';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Тануки ям';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Мидии чизу';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Мидии васаби';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Морской дракон';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Кумотори';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Цезарь c креветками';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Курица по-тайски с рисом';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Лимонад Мандарин-Юдзу 1000 мл 281';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Лимонад Классический 1000 мл 333';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Унаги торуфу';
UPDATE public.menu_items SET station = 'rolls_hot' WHERE title = 'Ролл Хотатэ авокадо';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Креветка васаби';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Хрустящий тунец';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Сифуд чиз';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Тунец Нисуаз';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Даку';
UPDATE public.menu_items SET station = 'rolls_hot' WHERE title = 'Ролл Теплый краб';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Мидори';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Эби тамаго';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Орандж микс';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Калифорния с лососем';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Карамельный угорь';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Тайгер';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Амуро';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Юмико';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Мексиканский';
UPDATE public.menu_items SET station = 'rolls_hot' WHERE title = 'Ролл Запеченный краб';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Дракон';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Филадельфия лайт';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Эби блючиз';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Чеддер';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Карри шримп';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Ролл Окинава';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Маки с угрем';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Маки с тунцом';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Маки с лососем';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Маки с авокадо';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Маки с огурцом';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Суши тамаго';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Суши опаленный лосось';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Суши с лососем';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Суши с угрем';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Суши с креветкой';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Суши с тунцом';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Гункан Чука';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Гункан Тобико';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Гункан Угорь спайси';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Гункан Креветка спайси';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Гункан Краб-микс спайси';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Гункан Гребешок спайси';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Гункан Лосось спайси';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Гункан Тунец спайси';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Темаки с лососем';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Темаки с угрем';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Темаки с крабом';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Сашими лосось';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Сашими угорь';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Сашими тунец';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Сашими креветка';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Сашими ассорти';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Маме с любовью';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Кавай сет';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Мураками сет';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Фудзи сет';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Онсен сет';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Сумико сет';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Аригато сет';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Ойши сет';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Тануки сет';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Party De Luxe';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Дим-самы с сочными овощами';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Дим-самы с лососем и креветкой';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Дим-самы с кальмаром и креветкой';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Дим-самы с крабом и креветкой';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Сифудо сет';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Мисо суп';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Бао';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Битые огурцы';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Брокколи стир фрай';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Эдамамэ солт';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Эдамамэ чили';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Овощи Теппан';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Тяхан с овощами';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Чука с ореховым соусом';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Картофель фри';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Рис на пару';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из грибов';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из кукурузы';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Спелый ананас';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Поке с лососем';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Вонтоны по-сычуаньски';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Креветки васаби';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Креветочные чипсы';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Креветки темпура';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Креветки в хрустящем тесте';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Гедза с креветками';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Гедза с курицей';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Поке с креветками';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Куриные крылышки';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Спринг-ролл с курицей';
UPDATE public.menu_items SET station = 'rolls_cold' WHERE title = 'Спринг-ролл с креветкой';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Калифорния спринг';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Дамплинги со свининой';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Кольца кальмара';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Тайский';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Баклажаны и томаты';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Зеленый океан';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Нисуаз';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Цезарь с курицей';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Кимчи со свининой';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Лакса';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Сябу с курицей и овощами';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Рамен с креветками';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Рамен с говядиной';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Сырный рамен';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Ребра барбекю с кукурузой';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Стейк семги';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Кацу чиз';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Утка по-пекински';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Лапша пад тай';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Курица в кисло-сладком соусе';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Говядина умисай';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Рис но-ми с креветками';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Рис но-ми со свининой';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Гюдон';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Тяхан с морепродуктами';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Тяхан с говядиной';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Тяхан с курицей';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Лапша с морепродуктами';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Лапша эби-ям';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Лапша с курицей';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Гречневая лапша с говядиной';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Японский мини-бургер';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Чикен спайси';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Унаги райс';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Якитори ассорти мясное';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Якитори ассорти морепродукты';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из лосося';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из тунца';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из креветки';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из кальмара';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из гребешка';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из мидий в беконе';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из говядины';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из курицы';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из куриных сердечек';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Шашлычок из перепелиных яиц';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Кастелло с клубникой и мятой';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Куро еру';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Наполеон-сан';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Малиновый сметанник';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Амаи миру';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Тирамису';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'MoMochi Зеленый чай';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'MoMochi Нежная ваниль';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'MoMochi Райский банан';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'MoMochi Бабл-гам';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'MoMochi Кокос баунти';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'MoMochi Тропический манго';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'MoMochi Красный апельсин';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'MoMochi Тройной шоколад';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Kid''  Box с наггетсами (с игрушкой)';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Kid''  Box с куриным бургером (с игрушкой)';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Куриные наггетсы с картофельным пюре';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Овощная соломка с сырным соусом';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Чуррос с клюквенным соусом';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Пельмешки со сметаной';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Наггетсы';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Суп с курочкой';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Суп с фрикадельками';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Макароны с сыром';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Бургер с курицей и картошкой фри';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Сырные палочки с клюквенным соусом';
UPDATE public.menu_items SET station = 'hot' WHERE title = 'Картошка фри';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Панкейки с шоколадом';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Шоколадный ролл';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Игра Memory 1 шт';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Имбирь';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Васаби';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Соевый соус';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Соус хойсин';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Соус тайский';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Соус спайси';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Соус шогояки';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Соус унаги';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Соус кохаку';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Соус гамадари';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Кетчуп';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Бабл-ти тайский кокос 450 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Бабл-ти ягодный 450 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Бабл-ти черника с шоколадом 450 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Бабл-ти бамбук-дыня-личи 450 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Яблочный фреш 500 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Апельсиновый фреш 500 мл 108';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Ананасовый фреш 500 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Грейпфрутовый фреш 500 мл 114';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Морковный фреш 500 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Сельдереевый фреш 500 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Яблоко-сельдерей 500 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Яблоко-сельдерей-морковь 500 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Морковь-сельдерей 500 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Лимонад Японская груша 1000 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Лимонад Тархун-Тимьян 1000 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Лимонад Крем-сода 1000 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Лимонад Гавайский бриз 1000 мл 211';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Лимонад Гавайский бриз без сахара 1000 мл 213';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Холодный чай Жасмин-вишня 1000 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Морс клюквенный 500 мл 231';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Морс клюквенный 1000 мл 163';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Морс вишневый 500 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Морс вишневый 1000 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Глинтвейн вишня-манго (б/а) 270 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Чай Конопляный';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Чай Малина-манго 600 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Чай Манго-маракуйя без сахара 600 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Чай Облепиха-имбирь 600 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Чай Облепиха-мандарин 600 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Чай Цитрусовый микс 600 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Чай Бора-Бора 600 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Яблочный сок 970 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Грейпфрутовый сок 970 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Яблочно-персиковый сок 970 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Ананасовый сок 970 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Апельсиновый сок 970 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Вишневый сок 970 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Томатный сок 970 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Липтон лимон 1000 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Липтон зеленый 1000 мл 125';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Everve  Cola 1000 мл 231';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Everve  Cola Zero 1000 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Фрустайл Лимон-лайм 1000 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Фрустайл Апельсин 1000 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Аква Минерале (без газа) 1000 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Аква Минерале (с газом) 1000 мл';
UPDATE public.menu_items SET station = 'drinks' WHERE title = 'Stella Artoi  non-alcoholic 440 мл';
UPDATE public.menu_items SET station = 'cold' WHERE title = 'Лед';
