UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/_ifg1SifWU4uafA8BqGYzr3NbNkBfm_T.png' WHERE title ILIKE '%ТАНУКИ%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/96762FnDYdK3wxnD52hv69CIhW9I_xIl.png' WHERE title ILIKE '%TVOЯ Pizza%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/bjQtUMXyTQks6GGhg5v7S-XoRBwrwSkW.png' WHERE title ILIKE '%Ёрш%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/0T5sNrjJxml0_dkARPZBl3CJuVW2YxoT.png' WHERE title ILIKE '%КАСПИЙКА%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/xBOMp0NxvORhlAcjJ4zkHqccZDs5seEM.png' WHERE title ILIKE '%Кейтеринг%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/I16rbOqE7Ittqy5uezKy_3zTMV8FDMY1.png' WHERE title ILIKE '%КАСПИЙКА Кейтеринг%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/2_KRfsoQoiJxT86-GlS6WyFYqxKqENMZ.jpg' WHERE title ILIKE '%Всем выбрали подарки?%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/S3btEm-mWvX8qLWKQL_mgnpmqp6PDJUV.png' WHERE title ILIKE '%Всем выбрали подарки? задний фон%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/9obEVXDrLncFXZS6Vx06i930KojpDe7K.png' WHERE title ILIKE '%Всем выбрали подарки? эмоджи%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Ls5xEgO-b9E7j4MINIXaJNWf3pP7rSno.jpg' WHERE title ILIKE '%Вопросы со вкусом%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/vN0c2LUgAFy4wgIW7Rbz50bOfbRWdZ3D.png' WHERE title ILIKE '%Вопросы со вкусом задний фон%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/-TKsOdttkxAB8dg9EohsVx_zNzlW26Qo.png' WHERE title ILIKE '%Вопросы со вкусом эмоджи%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/q7LWs8GY70hEYsCV7skpijF8b8Y1pIgE.jpg' WHERE title ILIKE '%По дороге с работы%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/0aKIDor6un5_guZd4EMKmAOHI8M-7591.png' WHERE title ILIKE '%По дороге с работы задний фон%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/nQrxCtLRuTcvrduwvd5qJMD39Hmc2v5w.png' WHERE title ILIKE '%По дороге с работы эмоджи%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/40_B9AgC5rrghkWzgliLeLNKG21Eix6L.jpg' WHERE title ILIKE '%Встречайте в Kidʼs box%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/C5Ll3iBvn2OLsu_p3C8rwSLVjXYJwWju.png' WHERE title ILIKE '%Встречайте в Kidʼs box задний фон%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ExpvHzG7xcNqp-oZX_tOs7LWD1OIma9m.png' WHERE title ILIKE '%Встречайте в Kidʼs box эмоджи%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/msaCi8qP3JDxDmihNxFmsXC-W6xcDW5r.jpg' WHERE title ILIKE '%Ролл Запеченный краб%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/SwQgVo8eEcslZuM-QbnmH4N1VQuBXa4Y.png' WHERE title ILIKE '%Острое%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/JMUpGK4cU50aT4jRMq1wYet0PMaOXaY0.jpg' WHERE title ILIKE '%Ролл Калифорния с лососем%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/kFR8ft9laT1a_7uO6ngzlYkkYME9CjXE.jpg' WHERE title ILIKE '%Ролл Филадельфия лайт%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/9p_zesruzTes9lqQxc73pHtJnbePDVzK.jpg' WHERE title ILIKE '%Ролл Окинава%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/2PN91WjtqEn1lNtmfhPWi5FWJc-VdEXn.jpg' WHERE title ILIKE '%Ролл Тайгер%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/du0TxQa7lI7yaxWdsEvIsHWeUT-caQAE.jpg' WHERE title ILIKE '%Ролл Креветка васаби%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/J2J-jcDwxkQet1_eLiYOeg3PdB9fcslr.jpg' WHERE title ILIKE '%Ролл Эби блючиз%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/9Tkf6PdvLP4O4_Itvq4jujp0uaEYUkZS.jpg' WHERE title ILIKE '%Ролл Теплый краб%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ffUor9blF6mjeCFwRdbPa8-LtxgLkb8X.jpg' WHERE title ILIKE '%Ролл Амуро%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/p20EthscreKOhAqJ8BFRvnY-zEtSJYlI.jpg' WHERE title ILIKE '%Ролл Мексиканский%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/GOQOD78qEFMKYRVpZZFtTZufekCDVLQ8.jpg' WHERE title ILIKE '%Ролл Дракон%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/9jPXNRQV5PQC8xHsC36JeecDGj7yV4Fd.jpg' WHERE title ILIKE '%Ролл Карри шримп%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/7-48WuoOPvk2Uj8_GlOVblUAow0_zczp.jpg' WHERE title ILIKE '%Ролл Орандж микс%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/lQw7Gw6g-JYg9xduHJPvlX2TNgHrYoYS.jpg' WHERE title ILIKE '%Ролл Тунец Нисуаз%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/wtVGUQXh8QSdJ5-iz_hzOU2rOc1NR8JK.jpg' WHERE title ILIKE '%Ролл Чеддер%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/tpkf9eE03Pu724vZDSI_K-Rhug_WjAc5.jpg' WHERE title ILIKE '%Ролл Эби тамаго%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/3XX9nHRZrtGAFJdOim5JKODxgnB_LpXv.jpg' WHERE title ILIKE '%Ролл Карамельный угорь%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/G1eZi_w8YiwN9VAC66pcqLoRO2YJiZa3.jpg' WHERE title ILIKE '%Ролл Сифуд чиз%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/N7iL-zKlurPyzegAhEluDqC03S_Srlsf.jpg' WHERE title ILIKE '%Ролл Хрустящий тунец%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/JtXtNpngeMpe-LCimkW76AQ4CW7BlEY0.jpg' WHERE title ILIKE '%Ролл Мидори%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/hn_mmrj2lNlbokQOLFG_aQGl_Ryw-o86.jpg' WHERE title ILIKE '%Ролл Даку%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/8XuvWSxxJ0LRrJ-2qOrS6uL9dp7z3KT6.jpg' WHERE title ILIKE '%Ролл Хотатэ авокадо%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/VnVLcVornnHG0z20PLZxe5UK52f529c2.jpg' WHERE title ILIKE '%Ролл Унаги торуфу%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/2PH-g02tZ6lPTwujh-5wu6GqdDtDyUCF.jpg' WHERE title ILIKE '%Ролл Юмико%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/vqURCQc5Eu4wGMC7zh0IvS7JbneFnYQQ.jpg' WHERE title ILIKE '%Маки с угрем%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/WhE1uNXkdwRcFkUCbWebOidtaTTuMith.jpg' WHERE title ILIKE '%Маки с тунцом%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/_0-Py3AC1UOeyzelKlfZcNZvLj4E307z.jpg' WHERE title ILIKE '%Маки с лососем%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/dOI518aAqpRpY-G6CnAwZVeNsA6tDIfG.jpg' WHERE title ILIKE '%Шоколадный ролл%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/hCGrLMK0tOlxBSmC1gg3WM4vkuu1INAi.jpg' WHERE title ILIKE '%Kid&#39;s Box с куриным бургером (с игрушкой)%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/HvFYn71nCgwMvj_gH6XOZFF7Q8OO9BBm.jpg' WHERE title ILIKE '%Ролл Аригато%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/LzMHzh4vNW8ycW6ncb956gFVekMxcG-u.png' WHERE title ILIKE '%Хиты%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/szUvNCwGe8HdfueHCKZm1K4Ve1DnPQoy.jpg' WHERE title ILIKE '%Ролл Калифорния%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/bGKgANHokw3vlcQDkmCdtyvKZ2auVAkw.jpg' WHERE title ILIKE '%Ролл Тануки%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/n1t9PDOlZbcfEKVaVOOTexPSgoQdzItz.jpg' WHERE title ILIKE '%Ролл Снегопад%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/3ozCwA6_NBH4rSzb2dYPlLF3OEZKoYO7.png' WHERE title ILIKE '%Новинки%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/kpvl0c7AAffXsIidY8Zz_4PD16RmI1zB.jpg' WHERE title ILIKE '%Спринг-ролл с креветкой%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/mmqiRc8CzuipKoig2wcOFlMZhGSVdcGc.jpg' WHERE title ILIKE '%Ролл Мишура%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/LBCLiTX2Kulc2rgv99hdiFmmLYmYgtFh.jpg' WHERE title ILIKE '%Ролл Когасэ%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/wsRBA8bpW1TIgxglTGh1rZjrhFNlc1va.jpg' WHERE title ILIKE '%Ролл Санта%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/E9XaBPPrKjELnoNWk1K5heDaEcioAv2t.jpg' WHERE title ILIKE '%Ролл Калифорния Хот%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/c7FUCU-IvNUT7QQ_yWFFjS1ziBk3jXxn.jpg' WHERE title ILIKE '%Спринг-ролл с курицей%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/6JaZ7OsE4-shYQ__isB6b9CxlADuJr85.jpg' WHERE title ILIKE '%Ролл Филадельфия%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/3gSVvJmrHdkZbnx2wQ8fHOg2FtCzk5q9.jpg' WHERE title ILIKE '%Ролл Прайм%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/-RGTgQQ6EjpGIs2irEiPnIC_uVCP3qBN.jpg' WHERE title ILIKE '%Онсен сет%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/OS5oPYtpegHj3PHXkMUhK6QEIuWtcVs_.jpg' WHERE title ILIKE '%Кавай сет%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/rG13QuPi8s_01tQtTpAt4A8TdywuGMXf.jpg' WHERE title ILIKE '%Аригато сет%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/D84C0MnGf-dzZmNsOzaRD3uhxlTHzWCt.jpg' WHERE title ILIKE '%Фудзи сет%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/OUxnonWebmCfnyjNi0BATCxr2OwJ5EQz.jpg' WHERE title ILIKE '%Ойши сет%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/XBvpLkrGXiqkN8koM-0sVpIDMTo1xmvH.jpg' WHERE title ILIKE '%Party De Luxe%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/PZOAMEwIzluyIt_gtQ0H_q1XZexV9qdb.jpg' WHERE title ILIKE '%Маме с любовью%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/oTn-yN_ga3tBysPVm1XIDZBvLhUvt9CS.jpg' WHERE title ILIKE '%Тануки сет%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Fk_SzhTZ4d2JaJdvA4Apjx5zSPYpsCnp.jpg' WHERE title ILIKE '%Мураками сет%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/sOgg-GtV8NYt8dUT4XDJDJdd3yjVrDiQ.jpg' WHERE title ILIKE '%Сумико сет%' AND (image_url IS NULL OR image_url = '');
UPDATE public.menu_items SET image_url = 'https://top-fwz1.mail.ru/counter?id=3320893;js=na' WHERE title ILIKE '%Top.Mail.Ru%' AND (image_url IS NULL OR image_url = '');
