UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/brands/1/96762FnDYdK3wxnD52hv69CIhW9I_xIl.png' WHERE title = 'TVOЯ Pizza';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/brands/1/I16rbOqE7Ittqy5uezKy_3zTMV8FDMY1.png' WHERE title = 'КАСПИЙКА Кейтеринг';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/bnr/1/2_KRfsoQoiJxT86-GlS6WyFYqxKqENMZ.jpg' WHERE title = 'Всем выбрали подарки?';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/bnr/1/Ls5xEgO-b9E7j4MINIXaJNWf3pP7rSno.jpg' WHERE title = 'Вопросы со вкусом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/bnr/1/q7LWs8GY70hEYsCV7skpijF8b8Y1pIgE.jpg' WHERE title = 'По дороге с работы';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/bnr/1/40_B9AgC5rrghkWzgliLeLNKG21Eix6L.jpg' WHERE title = 'Встречайте в Kidʼs box';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/msaCi8qP3JDxDmihNxFmsXC-W6xcDW5r.jpg' WHERE title = 'Ролл Запеченный краб';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/JMUpGK4cU50aT4jRMq1wYet0PMaOXaY0.jpg' WHERE title = 'Ролл Калифорния с лососем';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/kFR8ft9laT1a_7uO6ngzlYkkYME9CjXE.jpg' WHERE title = 'Ролл Филадельфия лайт';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/9p_zesruzTes9lqQxc73pHtJnbePDVzK.jpg' WHERE title = 'Ролл Окинава';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/2PN91WjtqEn1lNtmfhPWi5FWJc-VdEXn.jpg' WHERE title = 'Ролл Тайгер';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/du0TxQa7lI7yaxWdsEvIsHWeUT-caQAE.jpg' WHERE title = 'Ролл Креветка васаби';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/J2J-jcDwxkQet1_eLiYOeg3PdB9fcslr.jpg' WHERE title = 'Ролл Эби блючиз';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/9Tkf6PdvLP4O4_Itvq4jujp0uaEYUkZS.jpg' WHERE title = 'Ролл Теплый краб';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ffUor9blF6mjeCFwRdbPa8-LtxgLkb8X.jpg' WHERE title = 'Ролл Амуро';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/p20EthscreKOhAqJ8BFRvnY-zEtSJYlI.jpg' WHERE title = 'Ролл Мексиканский';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/GOQOD78qEFMKYRVpZZFtTZufekCDVLQ8.jpg' WHERE title = 'Ролл Дракон';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/9jPXNRQV5PQC8xHsC36JeecDGj7yV4Fd.jpg' WHERE title = 'Ролл Карри шримп';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/7-48WuoOPvk2Uj8_GlOVblUAow0_zczp.jpg' WHERE title = 'Ролл Орандж микс';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/lQw7Gw6g-JYg9xduHJPvlX2TNgHrYoYS.jpg' WHERE title = 'Ролл Тунец Нисуаз';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/wtVGUQXh8QSdJ5-iz_hzOU2rOc1NR8JK.jpg' WHERE title = 'Ролл Чеддер';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/tpkf9eE03Pu724vZDSI_K-Rhug_WjAc5.jpg' WHERE title = 'Ролл Эби тамаго';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/3XX9nHRZrtGAFJdOim5JKODxgnB_LpXv.jpg' WHERE title = 'Ролл Карамельный угорь';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/G1eZi_w8YiwN9VAC66pcqLoRO2YJiZa3.jpg' WHERE title = 'Ролл Сифуд чиз';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/N7iL-zKlurPyzegAhEluDqC03S_Srlsf.jpg' WHERE title = 'Ролл Хрустящий тунец';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/JtXtNpngeMpe-LCimkW76AQ4CW7BlEY0.jpg' WHERE title = 'Ролл Мидори';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/hn_mmrj2lNlbokQOLFG_aQGl_Ryw-o86.jpg' WHERE title = 'Ролл Даку';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/8XuvWSxxJ0LRrJ-2qOrS6uL9dp7z3KT6.jpg' WHERE title = 'Ролл Хотатэ авокадо';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/VnVLcVornnHG0z20PLZxe5UK52f529c2.jpg' WHERE title = 'Ролл Унаги торуфу';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/2PH-g02tZ6lPTwujh-5wu6GqdDtDyUCF.jpg' WHERE title = 'Ролл Юмико';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/vqURCQc5Eu4wGMC7zh0IvS7JbneFnYQQ.jpg' WHERE title = 'Маки с угрем';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/WhE1uNXkdwRcFkUCbWebOidtaTTuMith.jpg' WHERE title = 'Маки с тунцом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/_0-Py3AC1UOeyzelKlfZcNZvLj4E307z.jpg' WHERE title = 'Маки с лососем';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/dOI518aAqpRpY-G6CnAwZVeNsA6tDIfG.jpg' WHERE title = 'Шоколадный ролл';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/hCGrLMK0tOlxBSmC1gg3WM4vkuu1INAi.jpg' WHERE title = 'Kid&#39;s Box с куриным бургером (с игрушкой)';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/HvFYn71nCgwMvj_gH6XOZFF7Q8OO9BBm.jpg' WHERE title = 'Ролл Аригато';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/szUvNCwGe8HdfueHCKZm1K4Ve1DnPQoy.jpg' WHERE title = 'Ролл Калифорния';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/bGKgANHokw3vlcQDkmCdtyvKZ2auVAkw.jpg' WHERE title = 'Ролл Тануки';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/n1t9PDOlZbcfEKVaVOOTexPSgoQdzItz.jpg' WHERE title = 'Ролл Снегопад';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/kpvl0c7AAffXsIidY8Zz_4PD16RmI1zB.jpg' WHERE title = 'Спринг-ролл с креветкой';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/mmqiRc8CzuipKoig2wcOFlMZhGSVdcGc.jpg' WHERE title = 'Ролл Мишура';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/LBCLiTX2Kulc2rgv99hdiFmmLYmYgtFh.jpg' WHERE title = 'Ролл Когасэ';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/wsRBA8bpW1TIgxglTGh1rZjrhFNlc1va.jpg' WHERE title = 'Ролл Санта';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/E9XaBPPrKjELnoNWk1K5heDaEcioAv2t.jpg' WHERE title = 'Ролл Калифорния Хот';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/c7FUCU-IvNUT7QQ_yWFFjS1ziBk3jXxn.jpg' WHERE title = 'Спринг-ролл с курицей';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/6JaZ7OsE4-shYQ__isB6b9CxlADuJr85.jpg' WHERE title = 'Ролл Филадельфия';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/3gSVvJmrHdkZbnx2wQ8fHOg2FtCzk5q9.jpg' WHERE title = 'Ролл Прайм';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/-RGTgQQ6EjpGIs2irEiPnIC_uVCP3qBN.jpg' WHERE title = 'Онсен сет';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/OS5oPYtpegHj3PHXkMUhK6QEIuWtcVs_.jpg' WHERE title = 'Кавай сет';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/rG13QuPi8s_01tQtTpAt4A8TdywuGMXf.jpg' WHERE title = 'Аригато сет';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/D84C0MnGf-dzZmNsOzaRD3uhxlTHzWCt.jpg' WHERE title = 'Фудзи сет';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/OUxnonWebmCfnyjNi0BATCxr2OwJ5EQz.jpg' WHERE title = 'Ойши сет';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/XBvpLkrGXiqkN8koM-0sVpIDMTo1xmvH.jpg' WHERE title = 'Party De Luxe';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/PZOAMEwIzluyIt_gtQ0H_q1XZexV9qdb.jpg' WHERE title = 'Маме с любовью';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/oTn-yN_ga3tBysPVm1XIDZBvLhUvt9CS.jpg' WHERE title = 'Тануки сет';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Fk_SzhTZ4d2JaJdvA4Apjx5zSPYpsCnp.jpg' WHERE title = 'Мураками сет';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/sOgg-GtV8NYt8dUT4XDJDJdd3yjVrDiQ.jpg' WHERE title = 'Сумико сет';
UPDATE public.menu_items SET image_url = 'https://top-fwz1.mail.ru/counter' WHERE title = 'Top.Mail.Ru';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/fW4kDxL_T4i9qPYv1Ic-GKxXMzgF_rCc.jpg' WHERE title = 'Джингл сет';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/vZskv82H1HmllLbhYBqd8qeEH_wGCRRd.jpg' WHERE title = 'Чай Гринч';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/4xcEuZNvjQcMiEpi5keas7AumIGYLMes.jpg' WHERE title = 'Чай Груша-конопля';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/2KwVDhVVjIqFiOabLbB3fdOaVWalBnpz.jpg' WHERE title = 'Бабл-ти кокосовый дзен';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/CuOfdSDeo8iTxIZNZSX3aCvhsn-UKj_R.jpg' WHERE title = 'Тануки ям';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/flYr3ZNEwf84JLcG0x7cKC5CeRoDiSFo.jpg' WHERE title = 'Мидии чизу';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/V2oHYDpnV6VTfmeftQMkE8Uv-X8Tv3Dm.jpg' WHERE title = 'Мидии васаби';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/d4RWVirOy0Vdh_Rn17yhUnsxVs7q8raI.jpg' WHERE title = 'Морской дракон';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/5qjY4Ioi_JR0P4ocuQPn7xpYMQtHIqrL.jpg' WHERE title = 'Кумотори';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/lSecUs8QdiKzNcjgYw_EH89h5Y931fRG.jpg' WHERE title = 'Цезарь c креветками';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ErAUDHIXFeEyuwfkoo43MTj9hDLtRf0H.jpg' WHERE title = 'Курица по-тайски с рисом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/TJ9Fvzmc0o_gmcSZm0jfD8c-GGypK9o0.jpg' WHERE title = 'Лимонад Мандарин-Юдзу';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Rg8tfXzrJMafD2asMdZbwANFnZavFaFT.jpg' WHERE title = 'Лимонад Классический';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/OfC8_Hek98LwwuBb0Lg6ME2ll0DeiE5U.jpg' WHERE title = 'Маки с авокадо';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ooeixYuLqq23hVEPsV5KFwKz67Ns-HZ6.jpg' WHERE title = 'Маки с огурцом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/mk6fkkSrnyjVKtM5PpaiSFYjILdUL3lP.jpg' WHERE title = 'Суши тамаго';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/GjbqZ8VuY-lusXX1YkNNjxo-3p81a8pT.jpg' WHERE title = 'Суши опаленный лосось';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/_FCmL5Q32DL0tdYBNy9dqkK5M2NQHcA1.jpg' WHERE title = 'Суши с лососем';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/UvWW1CebVPbxlS79uvAcCx9G84pbVphB.jpg' WHERE title = 'Суши с угрем';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/vKc6927Dvdt7E1ife14Pleu9iQvJQXxU.jpg' WHERE title = 'Суши с креветкой';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/hhI5xQqaLXNXh7FgHTmJdq0sEQfdT55m.jpg' WHERE title = 'Суши с тунцом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/LEXMeOYQslX1TK-zOVNfvoqFM3I1R54z.jpg' WHERE title = 'Гункан Чука';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/vRLuhqZCMKgYMmd-1uWJWlDtFOhK4RZa.jpg' WHERE title = 'Гункан Тобико';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/-sWu0DS7LGgwNyzSwBkZVonqiAveMdvI.jpg' WHERE title = 'Гункан Угорь спайси';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/bz-TS0oNGr3rMlLDVfv4_b0ZPAJdsxZh.jpg' WHERE title = 'Гункан Креветка спайси';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/000HC9F5nEFObywwoPHuRnLgZouj4UvN.jpg' WHERE title = 'Гункан Краб-микс спайси';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/0fBxf324BQCBa_yuMwTV4kTv69i067oY.jpg' WHERE title = 'Гункан Гребешок спайси';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/zhVrVg5XfdX_2R0avciqUjng1yhf-_zj.jpg' WHERE title = 'Гункан Лосось спайси';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/wVvyJ1dL2Qe9vdNII6DWL3xem74St6yH.jpg' WHERE title = 'Гункан Тунец спайси';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/NYlAcFRWkK4C4wY5imVLmArojoLf7OGK.jpg' WHERE title = 'Темаки с лососем';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/jmHs72r9-YjAuyPWYmRYOp3wvaDTm2Mh.jpg' WHERE title = 'Темаки с угрем';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/vnzwt9acYLwYYju0WyGZ7tnrAg7Z4fRy.jpg' WHERE title = 'Темаки с крабом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/8_3vq-ltI5EfZU5h85Zlshou-Et3F8rl.jpg' WHERE title = 'Сашими лосось';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/RyTFf0EcpmKSGc3YAk_jKOAR2Mete2ZO.jpg' WHERE title = 'Сашими угорь';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/9nm7ufrKwa0PZFl5r_v1cl5J7SSQudeI.jpg' WHERE title = 'Сашими тунец';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Qyju-Re1pxpG4YN2lzgZ0aV9baIdjaxF.jpg' WHERE title = 'Сашими креветка';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/aelww7myLamferF0zO7ooa6j3hxe4qJl.jpg' WHERE title = 'Сашими ассорти';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/KiZCe93wJ9R1VBk2t_C5zt3vx_kzQNJE.jpg' WHERE title = 'Дим-самы с сочными овощами';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/byUXds-oKPoJcLZ6dV7CkTl0LQ-ERStj.jpg' WHERE title = 'Дим-самы с лососем и креветкой';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/KTtxfQ1CyP4Q12261FCJ8e86H2B2boDY.jpg' WHERE title = 'Дим-самы с кальмаром и креветкой';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/E7Q-iBZvmsV1jMfYMPg_fKFRUPwTRwPs.jpg' WHERE title = 'Дим-самы с крабом и креветкой';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/mJ9p-NTZgfex6QEZpEu08-GQAnPvrBIM.jpg' WHERE title = 'Сифудо сет';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/wnup7T_VtVhkTA_7TFzOEShVP8mBTAlF.jpg' WHERE title = 'Мисо суп';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/TpPA4vm-x-GVBnl6Edob6hVZF4scXXW3.jpg' WHERE title = 'Бао';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/uw3v3X3xp34RCG1vCinMcuOO1n06AeED.jpg' WHERE title = 'Битые огурцы';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/eYZXqoKHRCNtlE3qdCl5dKUkpjNJBfoB.jpg' WHERE title = 'Брокколи стир фрай';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/1Ck7IFtrM6r8e-l-zo5wjQiwBlE7MJci.jpg' WHERE title = 'Эдамамэ солт';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/1nD4Cccq0tP4ftka4lJGzFJkfW_m4Noi.jpg' WHERE title = 'Эдамамэ чили';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/B83gOA_yLKtjP5t100uDf-igm3YML-mG.jpg' WHERE title = 'Овощи Теппан';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/bucYnMeYvHeQN8aLl2LFe88ul1C6apt9.jpg' WHERE title = 'Тяхан с овощами';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/XLSdmMsNLdJGWXO2sx6ilAZd2TFzmQ0J.jpg' WHERE title = 'Чука с ореховым соусом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/63jlEfBwINM3pOoEue-6llTd0vBTwnT3.jpg' WHERE title = 'Картофель фри';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/M2TVAbOP-9JR4D7Yh9b576Fol-kO2JXg.jpg' WHERE title = 'Рис на пару';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/CBIfkPABXdXzBgz1tP6-uPbjZEqKbhMa.jpg' WHERE title = 'Шашлычок из грибов';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/hGAaZ1GpEenvI9obgZ13yoybT1Oj57Cq.jpg' WHERE title = 'Шашлычок из кукурузы';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/LiswJGDvkpJ0DBX0fKWntw6Dnxt36GVD.jpg' WHERE title = 'Спелый ананас';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/bgKakSYXD5mYs1dby_xD2hZ9jEoxfr-W.jpg' WHERE title = 'Поке с лососем';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/71CSYxtNemGat1dk6vFJ_FR2zyCt-wjW.jpg' WHERE title = 'Вонтоны по-сычуаньски';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/x_68H3PHgfc6tqW0xsWatljkTXUKk4AK.jpg' WHERE title = 'Креветки васаби';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/anCL8P3zhrxWkwjnLVsHA7ciDeu9dxDJ.jpg' WHERE title = 'Креветочные чипсы';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/rqm4As_0Pe4OelCih9a41pzHlTE13nzB.jpg' WHERE title = 'Креветки темпура';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ynLUoYnwl5rAJKtfaDwNm8BjqnqBE7hK.jpg' WHERE title = 'Креветки в хрустящем тесте';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/70xPBP_R3voqEWgBe4_MUhOZkz8fj0Eg.jpg' WHERE title = 'Гедза с креветками';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/-77lDyMmAE8P8J3PCz4Y4oIyB_L1nMj5.jpg' WHERE title = 'Гедза с курицей';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/6PV9If1dyp11LuHB7_tQaibOPi_tWSZp.jpg' WHERE title = 'Поке с креветками';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/NRU-tAT1NGAaVX7YuA-_33tBtsJlqMvH.jpg' WHERE title = 'Куриные крылышки';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ZSrX6-ojtjy92AZMQZC_40U6AGkQaJ56.jpg' WHERE title = 'Калифорния спринг';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/sp0g0-JiboQ-rSLOHvceWOuFzZKfVpXJ.jpg' WHERE title = 'Дамплинги со свининой';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/eP_aLwT67yn5DwcaoK9iuLG15icaQQ68.jpg' WHERE title = 'Кольца кальмара';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/1zyWT7Kdgi146cyk8zG5kGcnRzn7Gd_q.jpg' WHERE title = 'Тайский';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/2wmXqsZUdL6cqlC7euHYeXgKqsbCeYCD.jpg' WHERE title = 'Баклажаны и томаты';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/3zUdzEZFCca-qO9Lv-LJcALpdub6GIca.jpg' WHERE title = 'Зеленый океан';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/OC_q8xhW2LMG11TEfT_TVpBBNdzT3oVM.jpg' WHERE title = 'Нисуаз';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/51plDSsknKKuNMEm-ViC1Gum0G5FJoM4.jpg' WHERE title = 'Цезарь с курицей';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/6fDAz5r7nMZflXYSuXOTATki65_sZ9Vg.jpg' WHERE title = 'Кимчи со свининой';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/IUC8dXXsQFhTUCzoFhYiiKZeD9kDyjT8.jpg' WHERE title = 'Лакса';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/6R6tS0VA2j7E22x55E56oY2oHSWtzSPk.jpg' WHERE title = 'Сябу с курицей и овощами';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/5PUQbYo-HV3f0ZUCXpuRcUcRXskpNFcK.jpg' WHERE title = 'Рамен с креветками';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/RQnoFm-QQSCWdPSgBdGCdnR45XlxWKth.jpg' WHERE title = 'Рамен с говядиной';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Ag5LGw1C8gUQsEcFrUN43rJsITHMIM6T.jpg' WHERE title = 'Сырный рамен';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/JtRkkQrD0PdTt3n8vxU5zIyFCQ1U3QKg.jpg' WHERE title = 'Ребра барбекю с кукурузой';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/nVHFO35jc0JVSKZguKrenKAhVzhCzI6n.jpg' WHERE title = 'Стейк семги';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/-GIuMRMeEw7Tc-7moIZHf7TcEIONYVZu.jpg' WHERE title = 'Кацу чиз';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/WzuXnHy1P64823V_gMve9UNTWrI8rMbP.jpg' WHERE title = 'Утка по-пекински';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/eXVtsGrsrl2DHIyEk6w38Ayd0DxTD7dq.jpg' WHERE title = 'Лапша пад тай';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/GG_tx11nvR4uZucaOb5Oqb_RZrn4ap5v.jpg' WHERE title = 'Курица в кисло-сладком соусе';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/QMeMQZ-vxtjKOCVbxg-HWXFo1FqZ7GpH.jpg' WHERE title = 'Говядина умисай';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Wq0p-8igTThyX6lp440wP8JWtm93Srd0.jpg' WHERE title = 'Рис но-ми с креветками';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/FPTXUHRHaKLX4IyL6IE0pFIss7ne9zkc.jpg' WHERE title = 'Рис но-ми со свининой';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/LHGq-ZPnvjULVUVwLxHq_g_160J85oD2.jpg' WHERE title = 'Гюдон';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/UmTM1KN4issLXxra_5XimRnFE_59Y5dD.jpg' WHERE title = 'Тяхан с морепродуктами';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/BNWK3tsp9fsxv8Cmbv_9UZ5aAPA6hP3x.jpg' WHERE title = 'Тяхан с говядиной';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/DhPWvlP4vGiBgZd5ZaN9ogjLKZfDluJA.jpg' WHERE title = 'Тяхан с курицей';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/6f6gTluWUUrepA4L-lob4MC6reOC20cs.jpg' WHERE title = 'Лапша с морепродуктами';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Vl3-o6VsuBVTIaqa3URjdp9ABLUFxhq1.jpg' WHERE title = 'Лапша эби-ям';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/l7oaNkSTmXO9e6uaCSo_0v2_fZxviBrI.jpg' WHERE title = 'Лапша с курицей';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/pDEvLbRS2s3MRFy8HlcZ-ke-DypoH_0T.jpg' WHERE title = 'Гречневая лапша с говядиной';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/FiVG9DrCP5fGvDxg4TIkDZPmKHbdnEnw.jpg' WHERE title = 'Японский мини-бургер';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/cTllLoa_4wHlyk3djBZ9BJqsJaAvjZ0N.jpg' WHERE title = 'Чикен спайси';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/y272hJ3SOXzKM1ahp-CxKnlOgTYXOLZe.jpg' WHERE title = 'Унаги райс';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ZVAVGAA9Lda-VmcCup4ITTDacKldgmho.jpg' WHERE title = 'Якитори ассорти мясное';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/nSiKUfLRz1sV9W88wXo6lpG2DgtKcS1K.jpg' WHERE title = 'Якитори ассорти морепродукты';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/wK5_q-u7RK1avTeaNt7OHGmkwaSFgwmO.jpg' WHERE title = 'Шашлычок из лосося';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Sg8yTdRBrD2IbUL_zc591T6Xfd2huECs.jpg' WHERE title = 'Шашлычок из тунца';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/K6WBWh4LT49Vu8APGnBRIf_kQ9il-LZ5.jpg' WHERE title = 'Шашлычок из креветки';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/uonIbxVV2Gxp9dVvotLCvbXyP80s0tjq.jpg' WHERE title = 'Шашлычок из кальмара';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/TEVWos8G6ySwzGZzTtM98mTz9U2C6Lva.jpg' WHERE title = 'Шашлычок из гребешка';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/l1Hz-ZBsmzZQn--qpa7790vwaETUgMnW.jpg' WHERE title = 'Шашлычок из мидий в беконе';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/EitIX0bv63AxNnQxhVVyOqwF34lFoRWQ.jpg' WHERE title = 'Шашлычок из говядины';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/qwTzuAHSZRLNILRXEcGpmnan30iU3_LM.jpg' WHERE title = 'Шашлычок из курицы';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/zZyS1m6g83Yp-3DHZGi1YE-uZooZEuxy.jpg' WHERE title = 'Шашлычок из куриных сердечек';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/UgQsReU-3r1aRgn7_LhGLwu7sjENzWcK.jpg' WHERE title = 'Шашлычок из перепелиных яиц';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/KUOasj7Ey4Fi-fyb-q7Tg4A3ojAiG71S.jpg' WHERE title = 'Кастелло с клубникой и мятой';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/RJYuNQcDAgwXlo2tZxJBCiiSTVKgrZTu.jpg' WHERE title = 'Куро еру';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/HRzR2hlKFWpzqTL2esa-oG0KGcfVLfrD.jpg' WHERE title = 'Наполеон-сан';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/cjgFVJL0wwr51YDskcOs7xH_lRrq2AK0.jpg' WHERE title = 'Малиновый сметанник';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/iSRW-VUzEvutle8G719zDvGDzeqXEzmj.jpg' WHERE title = 'Амаи миру';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/SdBLHCu2sQp1PZiY1Poo-ia9He4AareU.jpg' WHERE title = 'Тирамису';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Z1Ah4YeHaeIwEdD5L8AxGzmNVA36zSmD.jpg' WHERE title = 'MoMochi Ассорти';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/qsVY2b-LjWgOhT3fLYvyPoVHrCk7NMPF.jpg' WHERE title = 'MoMochi Зеленый чай';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/jmy8WlmpXuO4VtcH4OjzAYQLUZ8PbwDB.jpg' WHERE title = 'MoMochi Нежная ваниль';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ggIn2fnvzxRg9IYThL4w-r2YthB1YfGn.jpg' WHERE title = 'MoMochi Райский банан';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/2XMUxm_ga6TnQ_JPkc2bemyAiGcve956.jpg' WHERE title = 'MoMochi Бабл-гам';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/EpxsHzYHyAIc-q-iTdAmNfsV8L4mttc8.jpg' WHERE title = 'MoMochi Кокос баунти';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/FX60TLc8oB7-W9rw0YNFEo6hccxE39aT.jpg' WHERE title = 'MoMochi Тропический манго';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/OVykNuJgWz819Fq7FEo5ZIOQ32DrwXgb.jpg' WHERE title = 'MoMochi Красный апельсин';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/OVS9mdgVQuapEUlQ_I9yZ2XdskBkl2gX.jpg' WHERE title = 'MoMochi Тройной шоколад';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/FWFAGotOV4RKshI-TR2W37ztjv-Ae4Pp.jpg' WHERE title = 'Kid&#x27;s Box с наггетсами (с игрушкой)';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/hCGrLMK0tOlxBSmC1gg3WM4vkuu1INAi.jpg' WHERE title = 'Kid&#x27;s Box с куриным бургером (с игрушкой)';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/GSOpNh39EvEEEtrhVnxspKH36BQmxgyS.jpg' WHERE title = 'Куриные наггетсы с картофельным пюре';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/C2HvTokHiGpMHfQFNU9ouDFyXBAJtuYv.jpg' WHERE title = 'Овощная соломка с сырным соусом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/eYX4EpdOVWu8ru7BobRkc5TC0i4fUCUo.jpg' WHERE title = 'Чуррос с клюквенным соусом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/XkOKHLqTcgQM6xKWnUshAElPS_nfN32G.jpg' WHERE title = 'Пельмешки со сметаной';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/e5nRg1vaXmTrsTUGSKVeahOdT2CuE3md.jpg' WHERE title = 'Наггетсы';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/KwYfV-8acz8hgbImEKHLsOutmubAIYt6.jpg' WHERE title = 'Суп с курочкой';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/YExcVy0VcK-hYhiIPO9V-WOSGbiwckxT.jpg' WHERE title = 'Суп с фрикадельками';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/QfSBulw8BNwsBVX3nwFJGsc45GPRiLGB.jpg' WHERE title = 'Макароны с сыром';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/UZYChsY1-m7pIISvMEUEDLZH6jTqY_br.jpg' WHERE title = 'Бургер с курицей и картошкой фри';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/aa6s4g1pYxEwalV5gwvhTtYvb8kwujfL.jpg' WHERE title = 'Сырные палочки с клюквенным соусом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/bTMfcM1LLLFxh5IQGRv6_0IySjTk3wYS.jpg' WHERE title = 'Картошка фри';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/M5uH2_dIEuwqdfbW2tSnySwN4eta0gWs.jpg' WHERE title = 'Панкейки с шоколадом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/G-6JHDzB4iCwt5r7dziKwHWP2rKHN_QP.jpg' WHERE title = 'Игра Memory';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Vfhz50bCdKigPtM0acTzMv7Xlnd6856k.jpg' WHERE title = 'Имбирь';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/YZrAnhCOXUM__kT47_HbnisPxvSwS2BD.jpg' WHERE title = 'Васаби';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/fVKMdJR_9JBOBHUSty8KwYuAYM2VxzJw.jpg' WHERE title = 'Соевый соус';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/yslsrVImmLxsQQYa2DwGQO3tB6WCruKa.jpg' WHERE title = 'Соус хойсин';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/1PO1AHWfXFmgu1GIJ6JjCb6rtsJkIrja.jpg' WHERE title = 'Соус тайский';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/wYpGjkksP-m_ay6qt07KySO2KGC8P7gi.jpg' WHERE title = 'Соус спайси';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/eWoDMss1sdWil29cGcJCoF22S4uLUxjE.jpg' WHERE title = 'Соус шогояки';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/F_jknSjvUMmuRtAXejDrGiIAeqxqKv8T.jpg' WHERE title = 'Соус унаги';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/AlRbDVbC2lPHRT1TeShzVaG7Il-1bamD.jpg' WHERE title = 'Соус кохаку';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/UkGdYUkS2HQYgmQ4zZ4gcIfNt-to6vxT.jpg' WHERE title = 'Соус гамадари';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/kzy2u3_K2C0Hgmz0mXOW9hKz5mOgYHLc.jpg' WHERE title = 'Кетчуп';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/GNGipaClaxNj4pXxqm9zGS4zWU5Ok6AK.jpg' WHERE title = 'Бабл-ти тайский кокос';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/7jPiON_y3uF48sr1SapPYbgh33YyrCyV.jpg' WHERE title = 'Бабл-ти ягодный';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/so6qtaEMM4ozVza5KrHteKhTpN3N6-_B.jpg' WHERE title = 'Бабл-ти черника с шоколадом';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/jYNf8tJFR-2SwK11QTevR-DlL226zF1D.jpg' WHERE title = 'Бабл-ти бамбук-дыня-личи';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/lKmXW9q9pzatke2WfAnij76llp_wrpk5.jpg' WHERE title = 'Яблочный фреш';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/cuJS0YOjaVSjipKmBBVCPSzxdj1wuRrC.jpg' WHERE title = 'Апельсиновый фреш';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/qZzascFU1sukBmLpHFXxsOKlw_OU9iZR.jpg' WHERE title = 'Ананасовый фреш';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/iiJmwXANj5Gj7nVzkhk6ACZ4Ul0GPyVh.jpg' WHERE title = 'Грейпфрутовый фреш';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/34cVx3OrR-WlK0sXDBiRCNyLf3_ASPTD.jpg' WHERE title = 'Морковный фреш';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Hk4SXAqP31zWYSsBOyXaeVwtA7bS6Qjd.jpg' WHERE title = 'Сельдереевый фреш';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/4ryF0cAZh3GEIVZ4PuYN6n6ejbn6ruYm.jpg' WHERE title = 'Яблоко-сельдерей';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/6uCA5CH6xyS6LScLNbSgCkNDgAwcbOCK.jpg' WHERE title = 'Яблоко-сельдерей-морковь';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/I0UxDaKkqPiumFKzASzQeINuP3hAqlpk.jpg' WHERE title = 'Морковь-сельдерей';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/eRPce_3aElrZZEn4aij6YnyYynGdOWlP.jpg' WHERE title = 'Лимонад Японская груша';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/geWsWPnBIJPGh1t6ETvgLizIsiurL_ZI.jpg' WHERE title = 'Лимонад Тархун-Тимьян';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/9oZrL2Zr_ijG-Sh2BJ2m6XhaMEmTBt6N.jpg' WHERE title = 'Лимонад Крем-сода';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ZtH_33WbhnDualeiq-bzlY7KKCWmPvXV.jpg' WHERE title = 'Лимонад Гавайский бриз';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/PepsJKFhMHq-n1WUPBKLC_J-p7H_bcco.jpg' WHERE title = 'Лимонад Гавайский бриз без сахара';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/E4NXf8JlikX9snJYSuE_3NDnHqGr206E.jpg' WHERE title = 'Холодный чай Жасмин-вишня';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/aO1ysy-cpfCgGR8Z3RiRU5elH5zha4_H.jpg' WHERE title = 'Морс клюквенный';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/sVgBEHGE3xPDJCP7RHtDNDs7qpFB1pah.jpg' WHERE title = 'Морс вишневый';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/q4LXwKA3gGux--H1GDh2XzIVfotAFOHC.jpg' WHERE title = 'Глинтвейн вишня-манго (б/а)';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/p5fXUO_lHLCYj_kLLtROAn5ies8fkSU7.jpg' WHERE title = 'Чай Конопляный';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/s9kdXUTJotDxa8twyv8k6X0Wvo302GNc.jpg' WHERE title = 'Чай Малина-манго';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/WN6PLFayBgYdEr-Vk6hJD2gjE1MOMjuA.jpg' WHERE title = 'Чай Манго-маракуйя без сахара';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/rCrdbXPYXVs92UqWbPejG6ik4GotMIPR.jpg' WHERE title = 'Чай Облепиха-имбирь';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Jj3rHVOWKCnhQIQCHgk_rbXi6HKklhoY.jpg' WHERE title = 'Чай Облепиха-мандарин';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/vcL-ke7rLWzoJ-mZIlWRNKNsTo3Dso7m.jpg' WHERE title = 'Чай Цитрусовый микс';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/hOdBfiSlmmjkgHcyPSiDeU4ln1Lc2wq_.jpg' WHERE title = 'Чай Бора-Бора';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/7D0HOcFgWRdIjn6AcpN5M8r1pWpFdIXR.jpg' WHERE title = 'Яблочный сок';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/JbTV3U1wZRDutgHloG45SqCkEfqbH1XD.jpg' WHERE title = 'Грейпфрутовый сок';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/xZ7i_EOUsqTqRvPUyOEhrstVfCxWLQFK.jpg' WHERE title = 'Яблочно-персиковый сок';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/FAAHQPc4DDI7u_lj0-fKDQGPU2_kvHQu.jpg' WHERE title = 'Ананасовый сок';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ssSbwlRTH6HbXsnfTvZNjG13IFhKdvRb.jpg' WHERE title = 'Апельсиновый сок';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/DfZCGsblDb_3sTIXZN9hZB2GZHkP25K8.jpg' WHERE title = 'Вишневый сок';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/9602KFdF8Zr6uBCfcSTORu0uac-k8m1X.jpg' WHERE title = 'Томатный сок';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/wHAIQIl8ZO2MXdPosQ-QlyLduWQpNZIn.jpg' WHERE title = 'Липтон лимон';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/3LX36kJiUR1wrRTuzYATvRWaQJarEy_E.jpg' WHERE title = 'Липтон зеленый';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/DD3mimi3aOvJD_Sj-IFymRk4jRT4UD4d.jpg' WHERE title = 'Evervess Cola';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/b1pnQ0Ed28Vqql8abCV_sh_fu9G1vj6q.jpg' WHERE title = 'Evervess Cola Zero';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/wrrT5qtBNVt81YhIrhT9vA-AU6JbpU8z.jpg' WHERE title = 'Фрустайл Лимон-лайм';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/JtaA9089rrQmzsIXJzRB4fSuSWljIDny.jpg' WHERE title = 'Фрустайл Апельсин';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/AsESAq0Ej0tD-eo6M1BMxA45NZIjhwwa.jpg' WHERE title = 'Аква Минерале (без газа)';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/7VtgUefwSPByeOSHMXmQOQUSQJsmsmq6.jpg' WHERE title = 'Аква Минерале (с газом)';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/3azPGyM69Mx-6IA8JeE_P1qw5Mr22oXC.jpg' WHERE title = 'Stella Artois non-alcoholic';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/Pp3SioM07nQIe52ASBEF4WpOhYAkXpoy.jpg' WHERE title = 'Лед';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/ipRT7R-viSBccarTImdY8-2MOpGXUd5G.jpg' WHERE title = 'Свитшот «Ностальгия»';
UPDATE public.menu_items SET image_url = 'https://kcdn.tanuki.ru/images/1/wzasumYVze4Tl4Jnh1AHmtSZgaJcqP3j.jpg' WHERE title = 'Свитшот «Всем привет»';
